require File.expand_path(File.dirname(__FILE__)) + '/../../../test_helper'

require 'holidays/definition/generator/module'

class GeneratorModuleTests < Test::Unit::TestCase
  def setup
    @generator = Holidays::Definition::Generator::Module.new

    @files = ["file1.rb", "file2.rb"]
    @module_name = "TEST"
    @regions = [:test, :test2]
    @month_strings = ["first-string", "second-string"]
    @custom_methods = "custom-methods"
  end

  def subject
    @generator.call(
      @files,
      @module_name,
      @regions,
      @month_strings,
      @custom_methods,
    )
  end

  def test_generates_source
    expected = <<-EOF
# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: file1.rb, file2.rb
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module TEST # :nodoc:
    def self.defined_regions
      [:test, :test2]
    end

    def self.holidays_by_month
      {
          first-string,
second-string
      }
    end

    def self.custom_methods
      {
          custom-methods
      }
    end
  end
end
EOF

    assert_equal expected, subject
  end

  def test_module_name_contains_hyphen_handled_correctly
    @module_name = "TEST-WITH-HYPHEN"

    expected = <<-EOF
# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: file1.rb, file2.rb
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module TEST-WITH-HYPHEN # :nodoc:
    def self.defined_regions
      [:test, :test2]
    end

    def self.holidays_by_month
      {
          first-string,
second-string
      }
    end

    def self.custom_methods
      {
          custom-methods
      }
    end
  end
end
EOF

    assert_equal expected, subject
  end
end
