# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/il.yaml
class IlDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_il
    assert_equal "Exodus from Egypt", (Holidays.on(Date.civil(2024, 3, 23), [:il])[0] || {})[:name]

    assert_equal "Exodus from Egypt (day 7)", (Holidays.on(Date.civil(2023, 3, 12), [:il])[0] || {})[:name]

    assert_equal "Independence Day", (Holidays.on(Date.civil(2025, 4, 1), [:il])[0] || {})[:name]

    assert_equal "Thanksgiving", (Holidays.on(Date.civil(2026, 4, 22), [:il])[0] || {})[:name]

    assert_equal "Thanksgiving (day 2)", (Holidays.on(Date.civil(2024, 5, 13), [:il])[0] || {})[:name]

    assert_equal "Jewish New Year", (Holidays.on(Date.civil(2023, 9, 16), [:il])[0] || {})[:name]

    assert_equal "2nd New Year's Day", (Holidays.on(Date.civil(2025, 9, 24), [:il])[0] || {})[:name]

    assert_equal "Day of Atonement", (Holidays.on(Date.civil(2026, 9, 21), [:il])[0] || {})[:name]

    assert_equal "Feast of Tabernacles", (Holidays.on(Date.civil(2024, 10, 17), [:il])[0] || {})[:name]

    assert_equal "Rejoicing of the Torah", (Holidays.on(Date.civil(2025, 10, 15), [:il])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2024, 7, 9), [:il])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2026, 8, 15), [:il])[0] || {})[:name]

  end
end
