# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/ru.yaml
class RuDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_ru
{ Date.civil(2017, 1, 1) => 'Новый год',
  Date.civil(2017, 1, 2) => 'Новогодний праздник',
  Date.civil(2017, 1, 3) => 'Новогодний праздник',
  Date.civil(2017, 1, 4) => 'Новогодний праздник',
  Date.civil(2017, 1, 5) => 'Новогодний праздник',
  Date.civil(2017, 1, 7) => 'Рождество Христово',
  Date.civil(2017, 2, 23) => 'День защитника Отечества',
  Date.civil(2017, 3, 8) => 'Международный женский день',
  Date.civil(2017, 5, 1) => 'Праздник Весны и Труда',
  Date.civil(2017, 5, 9) => 'День Победы',
  Date.civil(2017, 6, 12) => 'День России',
  Date.civil(2017, 8, 22) => 'День Государственного флага Российской Федерации',
  Date.civil(2017, 11, 4) => 'День народного единства'
}.each do |date, name|
  assert_equal name, (Holidays.on(date, :ru)[0] || {})[:name]
end

  end
end
