# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/vi.yaml
class ViDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_vi
{Date.civil(2014,1,1) => 'Tết dương lịch',
 Date.civil(2014,4,30) => 'Ngày Giải phóng miền Nam, thống nhất đất nước',
 Date.civil(2014,5,1) => "Ngày Quốc tế Lao động",
 Date.civil(2014,9,2) => 'Quốc khánh'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :vi)[0] || {})[:name]
end

  end
end
