# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/cn.yaml
class CnDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_cn
{Date.civil(2012,1,1) => '元旦',
 Date.civil(2016,2,7) => '除夕',
 Date.civil(2016,2,8) => '春节',
 Date.civil(2016,2,9) => '年初二',
 Date.civil(2016,2,10) => '年初三',
 Date.civil(2016,2,11) => '年初四',
 Date.civil(2016,2,12) => '迎财神',
 Date.civil(2016,4,4) => '清明',
 Date.civil(2016,6,9) => '端午节',
 Date.civil(2016,9,15) => '中秋节',
 Date.civil(1949,10,1) => '国庆节',
 Date.civil(2016,10,1) => '国庆节'
}.each do |date, name|
   assert_equal name, (Holidays.on(date, :cn, :informal)[0] || {})[:name]
end

[Date.civil(2004,4,4), Date.civil(2005,4,4), Date.civil(2006,4,5),
 Date.civil(2007,4,5), Date.civil(2008,4,4), Date.civil(2009,4,4),
 Date.civil(2010,4,5)].each do |date|
  assert_equal '清明', Holidays.on(date, :cn)[0][:name]
end

  end
end
