# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/mu.yaml
class MuDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_mu
    assert_equal "New Year's Day", (Holidays.on(Date.civil(2012, 1, 1), [:mu])[0] || {})[:name]

    assert_equal "Abolition of Slavery", (Holidays.on(Date.civil(2022, 2, 1), [:mu])[0] || {})[:name]

    assert_equal "Labour Day", (Holidays.on(Date.civil(2023, 5, 1), [:mu])[0] || {})[:name]

    assert_equal "Christmas Day", (Holidays.on(Date.civil(2017, 12, 25), [:mu])[0] || {})[:name]

  end
end
