# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/uy.yaml
class UyDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_uy
    assert_equal "Año Nuevo", (Holidays.on(Date.civil(2012, 1, 1), [:uy])[0] || {})[:name]

    assert_equal "Dia Del Trabajador", (Holidays.on(Date.civil(2022, 5, 1), [:uy])[0] || {})[:name]

    assert_equal "Jura Constitución", (Holidays.on(Date.civil(2023, 7, 18), [:uy])[0] || {})[:name]

    assert_equal "Día Independencia", (Holidays.on(Date.civil(2023, 8, 25), [:uy])[0] || {})[:name]

    assert_equal "Navidad", (Holidays.on(Date.civil(2017, 12, 25), [:uy])[0] || {})[:name]

  end
end
