# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/pk.yaml
class PkDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_pk
  end
end
