# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/nz_calendar_dates.yaml
class Nz_calendar_datesDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_nz_calendar_dates
    assert_equal "New Year's Day", (Holidays.on(Date.civil(2007, 1, 1), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Day after New Year's Day", (Holidays.on(Date.civil(2007, 1, 2), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Waitangi Day", (Holidays.on(Date.civil(2007, 2, 6), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Good Friday", (Holidays.on(Date.civil(2007, 4, 6), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Easter Monday", (Holidays.on(Date.civil(2007, 4, 9), [:nz], [:informal])[0] || {})[:name]

    assert_equal "ANZAC Day", (Holidays.on(Date.civil(2007, 4, 25), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Christmas Day", (Holidays.on(Date.civil(2007, 12, 25), [:nz], [:informal])[0] || {})[:name]

    assert_equal "Boxing Day", (Holidays.on(Date.civil(2007, 12, 26), [:nz], [:informal])[0] || {})[:name]

    assert_equal "ANZAC Day", (Holidays.on(Date.civil(2015, 4, 25), [:nz])[0] || {})[:name]

    assert_equal "ANZAC Day", (Holidays.on(Date.civil(2016, 4, 25), [:nz])[0] || {})[:name]

    assert_equal "Waitangi Day", (Holidays.on(Date.civil(2015, 2, 6), [:nz])[0] || {})[:name]

    assert_equal "Waitangi Day", (Holidays.on(Date.civil(2016, 2, 6), [:nz])[0] || {})[:name]

  end
end
