# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/hr.yaml
class HrDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_hr
{Date.civil(2012,1,1) => 'Nova godina', 
 Date.civil(2012,1,6) => 'Sveta tri kralja', 
 Date.civil(2012,5,1) => 'Međunarodni praznik rada',
 Date.civil(2012,6,22) => 'Dan antifašističke borbe',
 Date.civil(2012,6,25) => 'Dan državnosti',
 Date.civil(2012,8,5) => 'Dan pobjede i domovinske zahvalnosti i dan hrvatskih branitelja',
 Date.civil(2012,8,15) => 'Velika Gospa',
 Date.civil(2012,10,8) => 'Dan neovisnosti',
 Date.civil(2012,11,1) => 'Dan svih svetih',
 Date.civil(2012,12,25) => 'Božić',
 Date.civil(2012,12,26) => 'Sveti Stjepan'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :hr, :informal)[0] || {})[:name]
end

# Tijelovo
[Date.civil(2008,5,22), Date.civil(2009,6,11), Date.civil(2010,6,3),
 Date.civil(2012,6,7), Date.civil(2013,5,30), Date.civil(2014,6,19)].each do |date|
  assert_equal 'Tijelovo', Holidays.on(date, :hr)[0][:name]
end

  end
end
