# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/mt_mt.yaml
class Mt_mtDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_mt_mt
{ Date.civil(2017, 1, 1) => 'L-Ewwel tas-Sena',
  Date.civil(2017, 2, 10) => "Nawfraġju ta' San Pawl",
  Date.civil(2017, 3, 19) => 'San Ġużepp',
  Date.civil(2017, 3, 31) => 'Jum il-Ħelsien',
  Date.civil(2017, 5, 1) => 'Jum il-Ħaddiem',
  Date.civil(2017, 6, 7) => 'Sette Giugno',
  Date.civil(2017, 6, 29) => 'L-Imnarja',
  Date.civil(2017, 8, 15) => 'Santa Marija',
  Date.civil(2017, 9, 8) => 'Jum il-Vitorja',
  Date.civil(2017, 9, 21) => 'Jum l-Indipendenza',
  Date.civil(2017, 12, 8) => 'Il-Kunċizzjoni',
  Date.civil(2017, 12, 13) => 'Jum ir-Repubblika',
  Date.civil(2017, 12, 25) => 'Il-Milied',
}.each do |date, name|
  assert_equal name, (Holidays.on(date, :mt_mt)[0] || {})[:name]
end

[Date.civil(2017, 4, 14), Date.civil(2018, 3, 30), Date.civil(2019, 4, 19)].each do |date|
  assert_equal 'Il-Ġimgħa l-Kbira', Holidays.on(date, :mt_mt)[0][:name]
end

  end
end
