# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/lr.yaml
class LrDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_lr
    assert_equal "Decoration Day", (Holidays.on(Date.civil(2018, 3, 14), [:lr])[0] || {})[:name]
assert_equal "Decoration Day", (Holidays.on(Date.civil(2019, 3, 13), [:lr])[0] || {})[:name]

    assert_equal "Fast and Prayer Day", (Holidays.on(Date.civil(2018, 4, 13), [:lr])[0] || {})[:name]
assert_equal "Fast and Prayer Day", (Holidays.on(Date.civil(2020, 4, 10), [:lr])[0] || {})[:name]

    assert_equal "National Thanksgiving Day", (Holidays.on(Date.civil(2018, 11, 1), [:lr])[0] || {})[:name]
assert_equal "National Thanksgiving Day", (Holidays.on(Date.civil(2019, 11, 7), [:lr])[0] || {})[:name]

  end
end
