# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/cy.yaml
class CyDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_cy
    assert_equal "Εθνική Ημέρα της Κύπρου", (Holidays.on(Date.civil(2023, 4, 1), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Ημέρα Ανεξαρτησίας", (Holidays.on(Date.civil(2023, 10, 1), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Πρωτοχρονιά", (Holidays.on(Date.civil(2011, 1, 1), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Θεοφάνεια", (Holidays.on(Date.civil(2011, 1, 6), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Μεγάλη Παρασκευή", (Holidays.on(Date.civil(2011, 4, 22), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Μεγάλο Σάββατο", (Holidays.on(Date.civil(1970, 4, 25), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Κυριακή του Πάσχα", (Holidays.on(Date.civil(1985, 4, 14), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Κυριακή του Πάσχα", (Holidays.on(Date.civil(2011, 4, 24), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Κυριακή του Πάσχα", (Holidays.on(Date.civil(2027, 5, 2), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Δευτέρα του Πάσχα", (Holidays.on(Date.civil(2046, 4, 30), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Πρωτομαγιά", (Holidays.on(Date.civil(2011, 5, 1), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Αγίου Πνεύματος", (Holidays.on(Date.civil(2011, 6, 13), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Αγίου Πνεύματος", (Holidays.on(Date.civil(2012, 6, 4), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Καθαρά Δευτέρα", (Holidays.on(Date.civil(2011, 3, 7), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Καθαρά Δευτέρα", (Holidays.on(Date.civil(2012, 2, 27), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Χριστούγεννα", (Holidays.on(Date.civil(2011, 12, 25), [:cy], [:informal])[0] || {})[:name]

    assert_equal "Δεύτερη ημέρα των Χριστουγέννων", (Holidays.on(Date.civil(2011, 12, 26), [:cy], [:informal])[0] || {})[:name]

  end
end
