# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/th.yaml
class ThDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_th
    assert_equal "New Year's Day", (Holidays.on(Date.civil(2016, 1, 1), [:th])[0] || {})[:name]

    assert_equal "Makha Bucha Day", (Holidays.on(Date.civil(2016, 3, 1), [:th])[0] || {})[:name]

    assert_equal "Chakri Memorial Day", (Holidays.on(Date.civil(2016, 4, 6), [:th])[0] || {})[:name]

    assert_equal "Songkran Day", (Holidays.on(Date.civil(2016, 4, 13), [:th])[0] || {})[:name]

    assert_equal "Songkran Festival", (Holidays.on(Date.civil(2016, 4, 16), [:th])[0] || {})[:name]

    assert_equal "National Labour Day", (Holidays.on(Date.civil(2016, 5, 1), [:th])[0] || {})[:name]

    assert_equal "Wisakha Bucha Day", (Holidays.on(Date.civil(2016, 5, 29), [:th])[0] || {})[:name]

    assert_equal "Asarnha Bucha Day", (Holidays.on(Date.civil(2016, 7, 27), [:th])[0] || {})[:name]

    assert_equal "H.M. King Maha Vajiralongkorn Bodindradebayavarangkun's Birthday", (Holidays.on(Date.civil(2016, 7, 28), [:th], [:observed])[0] || {})[:name]

    assert_equal "H.M. Queen Sirikit's Birthday", (Holidays.on(Date.civil(2016, 8, 12), [:th], [:observed])[0] || {})[:name]

    assert_equal "Commemoration of the Passing King Bhumibol", (Holidays.on(Date.civil(2016, 10, 13), [:th], [:observed])[0] || {})[:name]

    assert_equal "Chulalongkorn Day", (Holidays.on(Date.civil(2016, 10, 23), [:th])[0] || {})[:name]

    assert_equal "Late King Bhumibol Adulyadej's Birthday, National Day and National Father's Day", (Holidays.on(Date.civil(2016, 12, 5), [:th])[0] || {})[:name]

    assert_equal "Constitution Day", (Holidays.on(Date.civil(2016, 12, 10), [:th])[0] || {})[:name]

    assert_equal "Year's End Day", (Holidays.on(Date.civil(2016, 12, 31), [:th])[0] || {})[:name]

  end
end
