# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/na.yaml
class NaDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_na
    assert_equal "New Years Days", (Holidays.on(Date.civil(2018, 1, 1), [:na])[0] || {})[:name]

    assert_equal "Good Friday", (Holidays.on(Date.civil(2018, 3, 30), [:na])[0] || {})[:name]

    assert_equal "Easter Monday", (Holidays.on(Date.civil(2018, 4, 2), [:na])[0] || {})[:name]

    assert_equal "Ascension Day", (Holidays.on(Date.civil(2018, 5, 10), [:na])[0] || {})[:name]

    assert_equal "Heroes' Day", (Holidays.on(Date.civil(2018, 8, 27), [:na])[0] || {})[:name]

    assert_equal "Easter Monday", (Holidays.on(Date.civil(2019, 4, 22), [:na])[0] || {})[:name]

    assert_equal "Ascension Day", (Holidays.on(Date.civil(2019, 5, 30), [:na])[0] || {})[:name]

    assert_equal "Heroes' Day", (Holidays.on(Date.civil(2019, 8, 26), [:na])[0] || {})[:name]

  end
end
