# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/cn.yaml
class CnDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_cn
    assert_equal "元旦", (Holidays.on(Date.civil(2025, 1, 1), [:cn])[0] || {})[:name]

    assert_equal "除夕", (Holidays.on(Date.civil(2025, 1, 28), [:cn])[0] || {})[:name]

    assert_equal "春节", (Holidays.on(Date.civil(2025, 1, 29), [:cn])[0] || {})[:name]

    assert_equal "春节", (Holidays.on(Date.civil(2025, 1, 30), [:cn])[0] || {})[:name]

    assert_equal "春节", (Holidays.on(Date.civil(2025, 1, 31), [:cn])[0] || {})[:name]

    assert_equal "春节", (Holidays.on(Date.civil(2024, 2, 10), [:cn])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2024, 2, 9), [:cn])[0] || {})[:name]

    assert_equal "除夕", (Holidays.on(Date.civil(2010, 2, 13), [:cn])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2010, 2, 16), [:cn])[0] || {})[:name]

    assert_equal "清明节", (Holidays.on(Date.civil(2025, 4, 4), [:cn])[0] || {})[:name]

    assert_equal "清明节", (Holidays.on(Date.civil(2026, 4, 5), [:cn])[0] || {})[:name]

    assert_equal "劳动节", (Holidays.on(Date.civil(2025, 5, 1), [:cn])[0] || {})[:name]

    assert_equal "劳动节", (Holidays.on(Date.civil(2025, 5, 2), [:cn])[0] || {})[:name]

    assert_nil (Holidays.on(Date.civil(2024, 5, 2), [:cn])[0] || {})[:name]

    assert_equal "端午节", (Holidays.on(Date.civil(2025, 5, 31), [:cn])[0] || {})[:name]

    assert_equal "端午节", (Holidays.on(Date.civil(2024, 6, 10), [:cn])[0] || {})[:name]

    assert_equal "中秋节", (Holidays.on(Date.civil(2024, 9, 17), [:cn])[0] || {})[:name]

    assert_equal "国庆节", (Holidays.on(Date.civil(2025, 10, 1), [:cn])[0] || {})[:name]

    assert_equal "国庆节", (Holidays.on(Date.civil(2025, 10, 2), [:cn])[0] || {})[:name]

    assert_equal "国庆节", (Holidays.on(Date.civil(2025, 10, 3), [:cn])[0] || {})[:name]

  end
end
