# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/united_nations.yaml
class United_nationsDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_united_nations

  end
end
