# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/rs_cyrl.yaml
class Rs_cyrlDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_rs_cyrl
{ Date.civil(2017, 1, 1) => 'Нова Година',
  Date.civil(2017, 1, 2) => 'Нова Година',
  Date.civil(2017, 1, 7) => 'Божић',
  Date.civil(2017, 1, 27) => 'Свети Сава (Савиндан)',
  Date.civil(2017, 2, 15) => 'Дан државности Србије',
  Date.civil(2017, 2, 16) => 'Дан државности Србије',
  Date.civil(2017, 5, 1) => 'Празник рада',
  Date.civil(2017, 5, 2) => 'Празник рада',
  Date.civil(2017, 5, 9) => 'Дан победе над фашизмом',
  Date.civil(2017, 6, 28) => 'Видовдан',
  Date.civil(2017, 11, 11) => 'Дан примирја'
}.each do |date, name|
  assert_equal name, (Holidays.on(date, :rs_cyrl)[0] || {})[:name]
end

[Date.civil(2017, 4, 14), Date.civil(2018, 4, 6), Date.civil(2019, 4, 26)].each do |date|
  assert_equal 'Велики петак', Holidays.on(date, :rs_cyrl)[0][:name]
end
[Date.civil(2017, 4, 15), Date.civil(2018, 4, 7), Date.civil(2019, 4, 27)].each do |date|
  assert_equal 'Велика Субота', Holidays.on(date, :rs_cyrl)[0][:name]
end
[Date.civil(2017, 4, 16), Date.civil(2018, 4, 8), Date.civil(2019, 4, 28)].each do |date|
  assert_equal 'Васкрс', Holidays.on(date, :rs_cyrl)[0][:name]
end
[Date.civil(2017, 4, 17), Date.civil(2018, 4, 9), Date.civil(2019, 4, 29)].each do |date|
  assert_equal 'Васкрсни понедељак', Holidays.on(date, :rs_cyrl)[0][:name]
end

  end
end
