# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/ee.yaml
class EeDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_ee
{Date.civil(2017,1,1) => 'Uusaasta',
 Date.civil(2017,2,24) => 'Iseseisvuspäev',
 Date.civil(2017,4,14) => 'Suur reede',
 Date.civil(2017,4,16) => 'Ülestõusmispühade 1. püha',
 Date.civil(2017,5,1) => 'Kevadpüha',
 Date.civil(2017,6,4) => 'Nelipühade 1. püha',
 Date.civil(2017,6,23) => 'Võidupüha ja jaanilaupäev',
 Date.civil(2017,6,24) => 'Jaanipäev',
 Date.civil(2017,8,20) => 'Taasiseseisvumispäev',
 Date.civil(2008,12,24) => 'Jõululaupäev',
 Date.civil(2008,12,25) => 'Esimene jõulupüha',
 Date.civil(2008,12,26) => 'Teine jõulupüha'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :ee, :informal)[0] || {})[:name]
end
  end
end
