# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/tr.yaml
class TrDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_tr
{ Date.civil(2017, 1, 1) => 'Yılbaşı',
  Date.civil(2017, 4, 23) => 'Ulusal Egemenlik ve Çocuk Bayramı',
  Date.civil(2017, 5, 1) => 'Emek ve Dayanışma Günü',
  Date.civil(2017, 5, 19) => "Atatürk'ü Anma Gençlik ve Spor Bayramı",
  Date.civil(2017, 8, 30) => 'Zafer Bayramı',
  Date.civil(2017, 10, 29) => 'Cumhuriyet Bayramı'
}.each do |date, name|
  assert_equal name, (Holidays.on(date, :tr)[0] || {})[:name]
end

[Date.civil(2017, 6, 25), Date.civil(2018, 6, 15), Date.civil(2019, 6, 4)].each do |date|
  assert_equal 'Ramazan Bayramı', Holidays.on(date, :tr)[0][:name]
end
[Date.civil(2017, 6, 26), Date.civil(2018, 6, 16), Date.civil(2019, 6, 5)].each do |date|
  assert_equal 'Ramazan Bayramı (ikinci tatil)', Holidays.on(date, :tr)[0][:name]
end
[Date.civil(2017, 6, 27), Date.civil(2018, 6, 17), Date.civil(2019, 6, 6)].each do |date|
  assert_equal 'Ramazan Bayramı (üçüncü tatil)', Holidays.on(date, :tr)[0][:name]
end

[Date.civil(2017, 9, 1), Date.civil(2018, 8, 21), Date.civil(2019, 8, 11)].each do |date|
  assert_equal 'Kurban Bayramı', Holidays.on(date, :tr)[0][:name]
end
[Date.civil(2017, 9, 2), Date.civil(2018, 8, 22), Date.civil(2019, 8, 12)].each do |date|
  assert_equal 'Kurban Bayramı (ikinci tatil)', Holidays.on(date, :tr)[0][:name]
end
[Date.civil(2017, 9, 3), Date.civil(2018, 8, 23), Date.civil(2019, 8, 13)].each do |date|
  assert_equal 'Kurban Bayramı (üçüncü tatil)', Holidays.on(date, :tr)[0][:name]
end
[Date.civil(2017, 9, 4), Date.civil(2018, 8, 24), Date.civil(2019, 8, 14)].each do |date|
  assert_equal 'Kurban Bayramı (dördüncü tatil)', Holidays.on(date, :tr)[0][:name]
end

  end
end
