# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/mc.yaml
class McDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_mc
    assert_equal "Jour de l'an", (Holidays.on(Date.civil(2026, 1, 1), [:mc])[0] || {})[:name]

    assert_equal "Sainte Dévote", (Holidays.on(Date.civil(2026, 1, 27), [:mc])[0] || {})[:name]

    assert_equal "Lundi de Pâques", (Holidays.on(Date.civil(2026, 4, 6), [:mc])[0] || {})[:name]

    assert_equal "Fête du Travail", (Holidays.on(Date.civil(2026, 5, 1), [:mc])[0] || {})[:name]

    assert_equal "Ascension", (Holidays.on(Date.civil(2026, 5, 14), [:mc])[0] || {})[:name]

    assert_equal "Lundi de Pentecôte", (Holidays.on(Date.civil(2026, 5, 25), [:mc])[0] || {})[:name]

    assert_equal "Fête Dieu", (Holidays.on(Date.civil(2026, 6, 4), [:mc])[0] || {})[:name]

    assert_equal "Assomption", (Holidays.on(Date.civil(2026, 8, 15), [:mc])[0] || {})[:name]

    assert_equal "Toussaint", (Holidays.on(Date.civil(2026, 11, 1), [:mc])[0] || {})[:name]

    assert_equal "Fête du Prince", (Holidays.on(Date.civil(2026, 11, 19), [:mc])[0] || {})[:name]

    assert_equal "Immaculée Conception", (Holidays.on(Date.civil(2026, 12, 8), [:mc])[0] || {})[:name]

    assert_equal "Noël", (Holidays.on(Date.civil(2026, 12, 25), [:mc])[0] || {})[:name]

    assert_equal "Immaculée Conception", (Holidays.on(Date.civil(2024, 12, 8), [:mc])[0] || {})[:name]

    assert_equal "Immaculée Conception", (Holidays.on(Date.civil(2024, 12, 9), [:mc], [:observed])[0] || {})[:name]

    assert_equal "Toussaint", (Holidays.on(Date.civil(2026, 11, 1), [:mc])[0] || {})[:name]

    assert_equal "Toussaint", (Holidays.on(Date.civil(2026, 11, 2), [:mc], [:observed])[0] || {})[:name]

  end
end
