# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/pe.yaml
class PeDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_pe
{Date.civil(2016,1,1) => 'Año Nuevo',
 Date.civil(2016,1,6) => 'Día de los Reyes Magos',
 Date.civil(2016,3,24) => 'Jueves Santo',
 Date.civil(2016,3,25) => 'Viernes Santo',
 Date.civil(2016,3,27) => 'Pascua',
 Date.civil(2016,5,1) => 'Día del Trabajador',
 Date.civil(2016,5,8) => 'Día de la Madre',
 Date.civil(2016,6,7) => 'Día de la Bandera',
 Date.civil(2016,6,19) => 'Día del Padre',
 Date.civil(2016,6,29) => 'San Pablo y San Pedro',
 Date.civil(2016,7,28) => 'Primer Día de la Independencia',
 Date.civil(2016,7,29) => 'Segundo Día de la Independencia',
 Date.civil(2016,8,30) => 'Santa Rosa de Lima',
 Date.civil(2016,9,24) => 'Día de las Fuerzas Armadas',
 Date.civil(2016,10,8) => 'Batalla de Angamos',
 Date.civil(2016,11,1) => 'Todos los Santos',
 Date.civil(2016,12,8) => 'Inmaculada Concepción',
 Date.civil(2016,12,25) => 'Navidad del Señor'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :pe, :informal)[0] || {})[:name]
end

  end
end
