# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: definitions/be_nl.yaml
class Be_nlDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_be_nl
{Date.civil(2007,1,1) => 'Nieuwjaar',
 Date.civil(2007,4,8) => 'Pasen',
 Date.civil(2007,4,9) => 'Paasmaandag',
 Date.civil(2007,5,1) => 'Feest van de Arbeid',
 Date.civil(2007,5,17) => 'O.H. Hemelvaart',
 Date.civil(2007,5,27) => 'Pinksteren',
 Date.civil(2007,5,28) => 'Pinkstermaandag',
 Date.civil(2007,7,21) => 'Nationale Feestdag',
 Date.civil(2007,8,15) => 'O.L.V. Hemelvaart',
 Date.civil(2007,11,1) => 'Allerheiligen',
 Date.civil(2007,11,11) => 'Wapenstilstand 1918',
 Date.civil(2007,12,25) => 'Kerstmis'}.each do |date, name|
  assert_equal name, (Holidays.on(date, :be_nl, :informal)[0] || {})[:name]
end

  end
end
