module HebCal
  module PassoverConstants
    HALAKIM_PER_HOUR = 1080
    HALAKIM_PER_DAY = 24 * HALAKIM_PER_HOUR
    ANNUAL_DRIFT = 10 * HALAKIM_PER_DAY + 21 * HALAKIM_PER_HOUR + 204
    JULIAN_ANNUAL_CALENDAR_DRIFT = HALAKIM_PER_HOUR * 6
    JULIAN_YEAR = 365.25 * HALAKIM_PER_DAY

    LUNAR_CYCLE = 29 * HALAKIM_PER_DAY + 12 * HALAKIM_PER_HOUR + 793
    HALAKIM_PER_19_YEAR_CYCLE = 235 * LUNAR_CYCLE

    JULIAN_ERROR_PER_19_YEAR_CYCLE = JULIAN_YEAR * 19 - HALAKIM_PER_19_YEAR_CYCLE
    EPOCH_TEKUFAH = -(20 * HALAKIM_PER_HOUR + 302)

    MOLAD_ZAQEN = 6 * HALAKIM_PER_HOUR
    TUTAKPAT = 15 * HALAKIM_PER_HOUR + 589
    TARAD = 9 * HALAKIM_PER_HOUR + 204
  end

  module HolidayConstants
    SHAVUOT_DISTANCE = 50
    SUKKOT_DISTANCE = 59 * 3
    PURIM_DISTANCE = -30
    FAST_AB_DISTANCE = 59 * 2 - 6
    STANDARD_HANUKAH_DISTANCE = 59 * 4 + 10
    STANDARD_10_TEVET_DISTANCE = 59 * 4 + 30 - 5
  end
end