# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/cme.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/cme'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module CME # :nodoc:
    def self.defined_regions
      [:cme]
    end

    def self.holidays_by_month
      {
              0 => [{:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :name => "Good Friday", :regions => [:cme]}],
      1 => [{:mday => 1, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "New Year's Day", :regions => [:cme]},
            {:wday => 1, :week => 3, :name => "Birthday of Martin Luther King, Jr", :regions => [:cme]}],
      2 => [{:wday => 1, :week => 3, :name => "President's Day", :regions => [:cme]}],
      5 => [{:wday => 1, :week => -1, :name => "Memorial Day", :regions => [:cme]}],
      7 => [{:mday => 4, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Independence Day", :regions => [:cme]}],
      9 => [{:wday => 1, :week => 1, :name => "Labor Day", :regions => [:cme]}],
      10 => [{:wday => 1, :week => 2, :name => "Columbus Day", :regions => [:cme]}],
      11 => [{:mday => 11, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Veterans Day", :regions => [:cme]},
            {:wday => 4, :week => 4, :name => "Thanksgiving Day", :regions => [:cme]}],
      12 => [{:mday => 25, :observed => lambda { |date| Holidays.to_monday_if_sunday(date) }, :observed_id => "to_monday_if_sunday", :name => "Christmas Day", :regions => [:cme]}]
      }
    end
  end

# January 20, every fourth year, following Presidential election
def self.us_inauguration_day(year)
  year % 4 == 1 ? 20 : nil
end

    



end

Holidays.merge_defs(Holidays::CME.defined_regions, Holidays::CME.holidays_by_month)
