module Holidays
  # This file is generated by the Ruby Holiday gem.
  #
  # Definitions loaded: data/ie.yaml, data/common_methods.yaml
  #
  # To use the definitions in the file, load them right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'path/to/ie'
  #
  # More definitions are available at http://code.dunae.ca/holidays.
  module IE # :nodoc:
    DEFINED_REGIONS = [:ie]

    HOLIDAYS_BY_MONTH = {
      5 => [{:wday => 1, :week => 1, :name => "May Day", :regions => [:ie]}],
      0 => [{:function => lambda { |year| easter(year)+1 }, :name => "Easter Monday", :regions => [:ie]}],
      6 => [{:wday => 1, :week => 1, :name => "Labour Day/May Day", :regions => [:ie]}],
      1 => [{:mday => 1, :name => "New Year's Day", :regions => [:ie]}],
      12 => [{:mday => 25, :name => "Christmas Day", :regions => [:ie]},
            {:mday => 26, :name => "St. Stephen's Day", :regions => [:ie]}],
      8 => [{:wday => 1, :week => 1, :name => "August Holiday", :regions => [:ie]}],
      3 => [{:mday => 17, :name => "St. Patrick's Day", :regions => [:ie]}],
      10 => [{:wday => 1, :week => -1, :name => "October Holiday", :regions => [:ie]}]
    }

# Get the date of Easter in a given year.
#
# +year+ must be a valid Gregorian year.
#
# Returns a Date object.
#--
# from http://snippets.dzone.com/posts/show/765
# TODO: check year to ensure Gregorian
def self.easter(year)
  y = year
  a = y % 19
  b = y / 100
  c = y % 100
  d = b / 4
  e = b % 4
  f = (b + 8) / 25
  g = (b - f + 1) / 3
  h = (19 * a + b - d - g + 15) % 30
  i = c / 4
  k = c % 4
  l = (32 + 2 * e + 2 * i - h - k) % 7
  m = (a + 11 * h + 22 * l) / 451
  month = (h + l - 7 * m + 114) / 31
  day = ((h + l - 7 * m + 114) % 31) + 1
  Date.civil(year, month, day)
end



  end
end

Holidays.merge_defs(Holidays::IE::DEFINED_REGIONS, Holidays::IE::HOLIDAYS_BY_MONTH)
