module Holidays
  # This file is generated by the Ruby Holiday gem.
  #
  # Definitions loaded: data/lv.yaml
  #
  # To use the definitions in this file, load them right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/lv'
  #
  # More definitions are available at http://code.dunae.ca/holidays.
  module LV # :nodoc:
    DEFINED_REGIONS = [:lv]

    HOLIDAYS_BY_MONTH = {
      5 => [{:mday => 1, :name => "Darba svetki", :regions => [:lv]},
            {:mday => 4, :name => "Neatkaribas deklaracijas pasludinašanas diena", :regions => [:lv]}],
      0 => [{:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :name => "Liela Piektdiena", :regions => [:lv]},
            {:function => lambda { |year| Holidays.easter(year) }, :function_id => "easter(year)", :name => "Lieldienas", :regions => [:lv]},
            {:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :name => "2. Lieldienas", :regions => [:lv]}],
      11 => [{:mday => 18, :name => "Latvijas Republikas proklamešanas diena", :regions => [:lv]}],
      6 => [{:mday => 23, :name => "Ligo Diena", :regions => [:lv]},
            {:mday => 24, :name => "Jani", :regions => [:lv]}],
      1 => [{:mday => 1, :name => "Jaunais Gads", :regions => [:lv]}],
      12 => [{:mday => 25, :name => "Ziemassvetki", :regions => [:lv]},
            {:mday => 25, :name => "2. Ziemassvetki", :regions => [:lv]},
            {:mday => 31, :name => "Vecgada vakars", :regions => [:lv]}]
    }
  end


end

Holidays.merge_defs(Holidays::LV::DEFINED_REGIONS, Holidays::LV::HOLIDAYS_BY_MONTH)
