module Holidays
  # This file is generated by the Ruby Holiday gem.
  #
  # Definitions loaded: data/nl.yaml
  #
  # To use the definitions in this file, load them right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/nl'
  #
  # More definitions are available at http://code.dunae.ca/holidays.
  module NL # :nodoc:
    DEFINED_REGIONS = [:nl]

    HOLIDAYS_BY_MONTH = {
      5 => [{:mday => 4, :name => "Dodenherdenking", :regions => [:nl]},
            {:mday => 5, :name => "Bevrijdingsdag", :regions => [:nl]}],
      0 => [{:function => lambda { |year| Holidays.easter(year)-2 }, :function_id => "easter(year)-2", :name => "Goede Vrijdag", :regions => [:nl]},
            {:function => lambda { |year| Holidays.easter(year) }, :function_id => "easter(year)", :name => "Pasen", :regions => [:nl]},
            {:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :name => "Pasen", :regions => [:nl]},
            {:function => lambda { |year| Holidays.easter(year)+39 }, :function_id => "easter(year)+39", :name => "Hemelvaartsdag", :regions => [:nl]},
            {:function => lambda { |year| Holidays.easter(year)+49 }, :function_id => "easter(year)+49", :name => "Pinksteren", :regions => [:nl]},
            {:function => lambda { |year| Holidays.easter(year)+50 }, :function_id => "easter(year)+50", :name => "Pinksteren", :regions => [:nl]}],
      1 => [{:mday => 1, :name => "Nieuwjaar", :regions => [:nl]}],
      12 => [{:mday => 5, :type => :informal, :name => "Sinterklaas", :regions => [:nl]},
            {:mday => 25, :name => "Kerstmis", :regions => [:nl]},
            {:mday => 26, :name => "Kerstmis", :regions => [:nl]}],
      4 => [{:mday => 30, :name => "Koninginnedag", :regions => [:nl]}]
    }
  end


end

Holidays.merge_defs(Holidays::NL::DEFINED_REGIONS, Holidays::NL::HOLIDAYS_BY_MONTH)
