module Holidays
  # This file is generated by the Ruby Holiday gem.
  #
  # Definitions loaded: data/nl.yaml, data/common_methods.yaml
  #
  # To use the definitions in the file, load them right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'path/to/nl'
  #
  # More definitions are available at http://code.dunae.ca/holidays.
  module NL # :nodoc:
    DEFINED_REGIONS = [:nl]

    HOLIDAYS_BY_MONTH = {
      5 => [{:mday => 4, :name => "Dodenherdenking", :regions => [:nl]},
            {:mday => 5, :name => "Bevrijdingsdag", :regions => [:nl]}],
      0 => [{:function => lambda { |year| easter(year)-2 }, :name => "Goede Vrijdag", :regions => [:nl]},
            {:function => lambda { |year| easter(year) }, :name => "Pasen", :regions => [:nl]},
            {:function => lambda { |year| easter(year)+1 }, :name => "Pasen", :regions => [:nl]},
            {:function => lambda { |year| easter(year)+39 }, :name => "Hemelvaartsdag", :regions => [:nl]},
            {:function => lambda { |year| easter(year)+49 }, :name => "Pinksteren", :regions => [:nl]},
            {:function => lambda { |year| easter(year)+50 }, :name => "Pinksteren", :regions => [:nl]}],
      1 => [{:mday => 1, :name => "Nieuwjaar", :regions => [:nl]}],
      12 => [{:mday => 5, :type => :informal, :name => "Sinterklaas", :regions => [:nl]},
            {:mday => 25, :name => "Kerstmis", :regions => [:nl]},
            {:mday => 26, :name => "Kerstmis", :regions => [:nl]}],
      4 => [{:mday => 30, :name => "Koninginnedag", :regions => [:nl]}]
    }

# Get the date of Easter in a given year.
#
# +year+ must be a valid Gregorian year.
#
# Returns a Date object.
#--
# from http://snippets.dzone.com/posts/show/765
# TODO: check year to ensure Gregorian
def self.easter(year)
  y = year
  a = y % 19
  b = y / 100
  c = y % 100
  d = b / 4
  e = b % 4
  f = (b + 8) / 25
  g = (b - f + 1) / 3
  h = (19 * a + b - d - g + 15) % 30
  i = c / 4
  k = c % 4
  l = (32 + 2 * e + 2 * i - h - k) % 7
  m = (a + 11 * h + 22 * l) / 451
  month = (h + l - 7 * m + 114) / 31
  day = ((h + l - 7 * m + 114) % 31) + 1
  Date.civil(year, month, day)
end



  end
end

Holidays.merge_defs(Holidays::NL::DEFINED_REGIONS, Holidays::NL::HOLIDAYS_BY_MONTH)
