module Holidays
  # This file is generated by the Ruby Holiday gem.
  #
  # Definitions loaded: data/united_nations.yaml
  #
  # To use the definitions in this file, load them right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/united_nations'
  #
  # More definitions are available at http://code.dunae.ca/holidays.
  module UNITED_NATIONS # :nodoc:
    DEFINED_REGIONS = [:]

    HOLIDAYS_BY_MONTH = {

    }
  end


end

Holidays.merge_defs(Holidays::UNITED_NATIONS::DEFINED_REGIONS, Holidays::UNITED_NATIONS::HOLIDAYS_BY_MONTH)
