# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/cn.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module CN # :nodoc:
    def self.defined_regions
      [:cn]
    end

    def self.holidays_by_month
      {
                1 => [{:mday => 1, :name => "元旦", :regions => [:cn]},
            {:mday => 1, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :function_modifier => -1, :year_ranges => { :between => 2008..2013 },:name => "除夕", :regions => [:cn]},
            {:mday => 1, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :function_modifier => -1, :year_ranges => { :from => 2025 },:name => "除夕", :regions => [:cn]},
            {:mday => 1, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :name => "春节", :regions => [:cn]},
            {:mday => 2, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :name => "春节", :regions => [:cn]},
            {:mday => 3, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :year_ranges => { :until => 2007 },:name => "春节", :regions => [:cn]},
            {:mday => 3, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :year_ranges => { :from => 2014 },:name => "春节", :regions => [:cn]}],
      4 => [{:function => "cn_qingming(year)", :function_arguments => [:year], :year_ranges => { :from => 2008 },:name => "清明节", :regions => [:cn]}],
      5 => [{:mday => 1, :name => "劳动节", :regions => [:cn]},
            {:mday => 2, :year_ranges => { :until => 2007 },:name => "劳动节", :regions => [:cn]},
            {:mday => 2, :year_ranges => { :from => 2025 },:name => "劳动节", :regions => [:cn]},
            {:mday => 3, :year_ranges => { :until => 2007 },:name => "劳动节", :regions => [:cn]},
            {:mday => 5, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :year_ranges => { :from => 2008 },:name => "端午节", :regions => [:cn]}],
      8 => [{:mday => 15, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :year_ranges => { :from => 2008 },:name => "中秋节", :regions => [:cn]}],
      10 => [{:mday => 1, :name => "国庆节", :regions => [:cn]},
            {:mday => 2, :name => "国庆节", :regions => [:cn]},
            {:mday => 3, :name => "国庆节", :regions => [:cn]}]
      }
    end

    def self.custom_methods
      {}
    end
  end
end
