# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/in.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module IN # :nodoc:
    def self.defined_regions
      [:in, :in_wb, :in_od, :in_tr, :in_mh, :in_ar, :in_mz, :in_br, :in_hp, :in_gj, :in_sk, :in_ts, :in_jh, :in_py, :in_kl, :in_ka, :in_jk, :in_ap, :in_cg, :in_hr, :in_mp, :in_pb, :in_nl, :in_as, :in_ga]
    end

    def self.holidays_by_month
      {
                0 => [{:function => "easter(year)", :function_arguments => [:year], :function_modifier => -2, :name => "Good Friday", :regions => [:in]},
            {:wday => 6, :week => 2, :type => :informal, :name => "Second Saturday Bank Holiday", :regions => [:in]},
            {:wday => 6, :week => 4, :type => :informal, :name => "Fourth Saturday Bank Holiday", :regions => [:in]}],
      1 => [{:mday => 1, :observed => "to_monday_if_weekend(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:in]},
            {:mday => 12, :name => "Swami Vivekananda Jayanti", :regions => [:in_wb]},
            {:mday => 14, :name => "Makar Sankranti / Pongal / Magh Bihu / Uttarayan / Khichdi / Sankranti", :regions => [:in]},
            {:mday => 23, :name => "Netaji Subhas Chandra Bose Jayanti", :regions => [:in_od, :in_wb, :in_tr]},
            {:mday => 26, :name => "Republic Day", :regions => [:in]}],
      2 => [{:mday => 19, :name => "Chhatrapati Shivaji Maharaj Jayanti", :regions => [:in_mh]},
            {:mday => 20, :name => "Arunachal Pradesh Statehood Day", :regions => [:in_ar]},
            {:mday => 20, :name => "Mizoram State Day", :regions => [:in_mz]}],
      3 => [{:mday => 22, :name => "Bihar Day", :regions => [:in_br]}],
      4 => [{:mday => 1, :name => "Odisha Day", :regions => [:in_od]},
            {:mday => 14, :name => "Dr. B. R. Ambedkar Jayanti", :regions => [:in]},
            {:mday => 15, :name => "Himachal Pradesh Day", :regions => [:in_hp]},
            {:mday => 15, :name => "West Bengal Day", :regions => [:in_wb]}],
      5 => [{:mday => 1, :name => "Labour Day", :regions => [:in]},
            {:mday => 1, :name => "Gujarat Day", :regions => [:in_gj]},
            {:mday => 1, :name => "Maharashtra Day", :regions => [:in_mh]},
            {:mday => 7, :name => "Rabindranath Tagore Jayanti", :regions => [:in_wb]},
            {:mday => 16, :name => "Sikkim State Day", :regions => [:in_sk]}],
      6 => [{:mday => 2, :name => "Telangana Formation Day", :regions => [:in_ts]}],
      7 => [{:mday => 13, :name => "Martyrs' Day", :regions => [:in_jh]}],
      8 => [{:mday => 15, :name => "Independence day", :regions => [:in]},
            {:mday => 16, :name => "Puducherry De Jure Transfer Day", :regions => [:in_py]},
            {:mday => 20, :name => "Sree Narayana Guru Jayanti", :regions => [:in_kl]}],
      9 => [{:mday => 17, :name => "Hyderabad-Karnataka Liberation Day", :regions => [:in_ka]}],
      10 => [{:mday => 2, :name => "Mahatma Gandhi Jayanti", :regions => [:in]},
            {:mday => 26, :name => "Jammu and Kashmir Association Day", :regions => [:in_jk]},
            {:mday => 31, :name => "Sardar Vallabhbhai Patel Jayanti", :regions => [:in_gj]}],
      11 => [{:mday => 1, :name => "Andhra Pradesh Day", :regions => [:in_ap]},
            {:mday => 1, :name => "Chhattisgarh Rajyotsava", :regions => [:in_cg]},
            {:mday => 1, :name => "Haryana Day", :regions => [:in_hr]},
            {:mday => 1, :name => "Kannada Rajyothsava", :regions => [:in_ka]},
            {:mday => 1, :name => "Kerala Day", :regions => [:in_kl]},
            {:mday => 1, :name => "Madhya Pradesh Day", :regions => [:in_mp]},
            {:mday => 1, :name => "Punjab Day", :regions => [:in_pb]},
            {:mday => 1, :name => "Puducherry Liberation Day", :regions => [:in_py]}],
      12 => [{:mday => 1, :name => "Nagaland State Inauguration Day", :regions => [:in_nl]},
            {:mday => 2, :name => "Asom Day", :regions => [:in_as]},
            {:mday => 19, :name => "Goa Liberation Day", :regions => [:in_ga]},
            {:mday => 25, :name => "Christmas Day", :regions => [:in]}]
      }
    end

    def self.custom_methods
      {
          
      }
    end
  end
end
