# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/mc.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module MC # :nodoc:
    def self.defined_regions
      [:mc]
    end

    def self.holidays_by_month
      {
                0 => [{:function => "easter(year)", :function_arguments => [:year], :function_modifier => 1, :name => "Lundi de Pâques", :regions => [:mc]},
            {:function => "easter(year)", :function_arguments => [:year], :function_modifier => 39, :name => "Ascension", :regions => [:mc]},
            {:function => "easter(year)", :function_arguments => [:year], :function_modifier => 50, :name => "Lundi de Pentecôte", :regions => [:mc]},
            {:function => "easter(year)", :function_arguments => [:year], :function_modifier => 60, :name => "Fête Dieu", :regions => [:mc]}],
      1 => [{:mday => 1, :name => "Jour de l'an", :regions => [:mc]},
            {:mday => 27, :name => "Sainte Dévote", :regions => [:mc]}],
      5 => [{:mday => 1, :name => "Fête du Travail", :regions => [:mc]}],
      8 => [{:mday => 15, :name => "Assomption", :regions => [:mc]}],
      11 => [{:mday => 1, :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Toussaint", :regions => [:mc]},
            {:mday => 19, :name => "Fête du Prince", :regions => [:mc]}],
      12 => [{:mday => 8, :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Immaculée Conception", :regions => [:mc]},
            {:mday => 25, :name => "Noël", :regions => [:mc]}]
      }
    end

    def self.custom_methods
      {
          
      }
    end
  end
end
