# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/nz_calendar_dates.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module NZ_CALENDAR_DATES # :nodoc:
    def self.defined_regions
      [:nz, :nz_sl, :nz_we, :nz_ak, :nz_nl, :nz_ne, :nz_ot, :nz_ta, :nz_sc, :nz_hb, :nz_mb, :nz_ca, :nz_ch, :nz_wl]
    end

    def self.holidays_by_month
      {
              0 => [{:function => "easter(year)", :function_arguments => [:year], :function_modifier => -2, :name => "Good Friday", :regions => [:nz]},
            {:function => "easter(year)", :function_arguments => [:year], :function_modifier => 1, :name => "Easter Monday", :regions => [:nz]}],
      1 => [{:mday => 1, :name => "New Year's Day", :regions => [:nz]},
            {:mday => 2, :name => "Day after New Year's Day", :regions => [:nz]},
            {:mday => 17, :name => "Southland Anniversary Day", :regions => [:nz_sl]},
            {:mday => 22, :name => "Wellington Anniversary Day", :regions => [:nz_we]},
            {:mday => 29, :name => "Auckland Anniversary Day", :regions => [:nz_ak]},
            {:mday => 29, :name => "Northland Anniversary Day", :regions => [:nz_nl]}],
      2 => [{:mday => 1, :name => "Nelson Anniversary Day", :regions => [:nz_ne]},
            {:mday => 6, :name => "Waitangi Day", :regions => [:nz]}],
      3 => [{:mday => 23, :name => "Otago Anniversary Day", :regions => [:nz_ot]},
            {:wday => 1, :week => 2, :name => "Taranaki Anniversary Day", :regions => [:nz_ta]}],
      4 => [{:mday => 25, :name => "ANZAC Day", :regions => [:nz]}],
      6 => [{:wday => 1, :week => 1, :name => "Queen's Birthday", :regions => [:nz]}],
      9 => [{:wday => 1, :week => 4, :name => "Dominion Day", :regions => [:nz_sc]}],
      10 => [{:wday => 1, :week => 1, :name => "Hawke's bay Anniversary Day", :regions => [:nz_hb]},
            {:wday => 1, :week => 4, :name => "Labour Day", :regions => [:nz]},
            {:wday => 1, :week => 4, :name => "Marlborough Anniversary Day", :regions => [:nz_mb]}],
      11 => [{:wday => 5, :week => 2, :name => "Canterbury Anniversary Day", :regions => [:nz_ca]},
            {:mday => 30, :name => "Chatham Island Anniversary Day", :regions => [:nz_ch]}],
      12 => [{:mday => 1, :name => "Westland Anniversary Day", :regions => [:nz_wl]},
            {:mday => 25, :name => "Christmas Day", :regions => [:nz]},
            {:mday => 26, :name => "Boxing Day", :regions => [:nz]}]
      }
    end

    def self.custom_methods
      {
        
      }
    end
  end
end
