# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/pk.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module PK # :nodoc:
    def self.defined_regions
      [:pk]
    end

    def self.holidays_by_month
      {
              2 => [{:mday => 4, :name => "Kashmir Day", :regions => [:pk]}],
      3 => [{:mday => 23, :name => "Pakistan Day", :regions => [:pk]}],
      5 => [{:mday => 1, :name => "Labour Day", :regions => [:pk]}],
      8 => [{:mday => 14, :name => "Independence Day", :regions => [:pk]}],
      12 => [{:mday => 25, :name => "Quaid-i-Azam Day", :regions => [:pk]}]
      }
    end

    def self.custom_methods
      {
        
      }
    end
  end
end
