# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/sg.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module SG # :nodoc:
    def self.defined_regions
      [:sg]
    end

    def self.holidays_by_month
      {
                0 => [{:function => "easter(year)", :function_arguments => [:year], :function_modifier => -2, :name => "Good Friday", :regions => [:sg]}],
      1 => [{:mday => 1, :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:sg]},
            {:mday => 1, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Chinese New Year", :regions => [:sg]},
            {:mday => 2, :function => "lunar_to_solar(year, month, day, region)", :function_arguments => [:year, :month, :day, :region], :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Chinese New Year", :regions => [:sg]}],
      2 => [{:mday => 14, :type => :informal, :name => "Valentine's Day", :regions => [:sg]},
            {:mday => 15, :type => :informal, :name => "Total Defence Day", :regions => [:sg]}],
      3 => [{:mday => 31, :year_ranges => { :limited => [2025] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 21, :year_ranges => { :limited => [2026] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]}],
      4 => [{:mday => 22, :year_ranges => { :limited => [2023] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 10, :year_ranges => { :limited => [2024] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]}],
      5 => [{:mday => 1, :name => "Labour Day", :regions => [:sg]},
            {:mday => 10, :year_ranges => { :limited => [2017] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 29, :year_ranges => { :limited => [2018] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 19, :year_ranges => { :limited => [2019] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 7, :year_ranges => { :limited => [2020] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 26, :year_ranges => { :limited => [2021] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 15, :year_ranges => { :limited => [2022] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 22, :year_ranges => { :limited => [2024] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 12, :year_ranges => { :limited => [2025] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 31, :year_ranges => { :limited => [2026] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 24, :year_ranges => { :limited => [2020] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 13, :year_ranges => { :limited => [2021] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 3, :year_ranges => { :limited => [2022] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 27, :year_ranges => { :limited => [2026] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]}],
      6 => [{:mday => 2, :year_ranges => { :limited => [2023] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Vesak Day", :regions => [:sg]},
            {:mday => 25, :year_ranges => { :limited => [2017] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 15, :year_ranges => { :limited => [2018] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 5, :year_ranges => { :limited => [2019] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Puasa", :regions => [:sg]},
            {:mday => 29, :year_ranges => { :limited => [2023] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]},
            {:mday => 17, :year_ranges => { :limited => [2024] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]},
            {:mday => 7, :year_ranges => { :limited => [2025] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]}],
      7 => [{:mday => 31, :year_ranges => { :limited => [2020] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]},
            {:mday => 20, :year_ranges => { :limited => [2021] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]},
            {:mday => 10, :year_ranges => { :limited => [2022] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]}],
      8 => [{:mday => 9, :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "National Day", :regions => [:sg]},
            {:mday => 22, :year_ranges => { :limited => [2018] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]},
            {:mday => 11, :year_ranges => { :limited => [2019] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]}],
      9 => [{:mday => 1, :year_ranges => { :limited => [2017] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Hari Raya Haji", :regions => [:sg]}],
      10 => [{:mday => 18, :year_ranges => { :limited => [2017] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 27, :year_ranges => { :limited => [2019] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 24, :year_ranges => { :limited => [2022] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 31, :year_ranges => { :limited => [2024] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 20, :year_ranges => { :limited => [2025] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]}],
      11 => [{:mday => 6, :year_ranges => { :limited => [2018] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 14, :year_ranges => { :limited => [2020] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 4, :year_ranges => { :limited => [2021] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 12, :year_ranges => { :limited => [2023] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]},
            {:mday => 8, :year_ranges => { :limited => [2026] },:observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Deepavali", :regions => [:sg]}],
      12 => [{:mday => 25, :observed => "to_monday_if_sunday(date)", :observed_arguments => [:date], :name => "Christmas Day", :regions => [:sg]}]
      }
    end

    def self.custom_methods
      {
          
      }
    end
  end
end
