# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: definitions/th.yaml
  #
  # All the definitions are available at https://github.com/holidays/holidays
  module TH # :nodoc:
    def self.defined_regions
      [:th]
    end

    def self.holidays_by_month
      {
              1 => [{:mday => 1, :observed => "to_monday_if_weekend(date)", :observed_arguments => [:date], :name => "New Year's Day", :regions => [:th]}],
      3 => [{:mday => 1, :name => "Makha Bucha Day", :regions => [:th]}],
      4 => [{:mday => 6, :name => "Chakri Memorial Day", :regions => [:th]},
            {:mday => 13, :name => "Songkran Day", :regions => [:th]},
            {:mday => 16, :name => "Songkran Festival", :regions => [:th]}],
      5 => [{:mday => 1, :name => "National Labour Day", :regions => [:th]},
            {:mday => 29, :name => "Wisakha Bucha Day", :regions => [:th]}],
      7 => [{:mday => 27, :name => "Asarnha Bucha Day", :regions => [:th]},
            {:mday => 28, :observed => "to_monday_if_weekend(date)", :observed_arguments => [:date], :name => "H.M. King Maha Vajiralongkorn Bodindradebayavarangkun's Birthday", :regions => [:th]}],
      8 => [{:mday => 12, :observed => "to_monday_if_weekend(date)", :observed_arguments => [:date], :name => "H.M. Queen Sirikit's Birthday", :regions => [:th]}],
      10 => [{:mday => 13, :observed => "to_monday_if_weekend(date)", :observed_arguments => [:date], :name => "Commemoration of the Passing King Bhumibol", :regions => [:th]},
            {:mday => 23, :name => "Chulalongkorn Day", :regions => [:th]}],
      12 => [{:mday => 5, :name => "Late King Bhumibol Adulyadej's Birthday, National Day and National Father's Day", :regions => [:th]},
            {:mday => 10, :name => "Constitution Day", :regions => [:th]},
            {:mday => 31, :name => "Year's End Day", :regions => [:th]}]
      }
    end

    def self.custom_methods
      {
        
      }
    end
  end
end
